---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-demo
  namespace: flux-demo
  labels:
    app: hello-app-demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.hello-app: semver:~1.0.0
    # can be <glob, semver and regexp>:
    # https://fluxcd.io/legacy/flux/references/fluxctl/#filter-pattern-typesss
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello-app-demo
  template:
    metadata:
      labels:
        app: hello-app-demo
    spec:
      containers:
      - name: hello-app-demo
        image: 591802062023.dkr.ecr.us-east-1.amazonaws.com/mywebapprepo:10
        ports:
        - name: hello-app-port
          containerPort: 3000
